name: Run Nightfall Integration test

on:
  push:
    branches:
    - liju.jose/configure-github-actions

jobs:
  eslint:
    name: check for eslint issues
    runs-on: ubuntu-16.04
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.15.3'
    - run: npm ci
    - run: npm run lint

  docker-setup:
    name: Pull docker image
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/docker/cli-multi@master
    - run:  docker pull zokrates/zokrates:0.4.11
    - name: Build image
    - run:  docker-compose build

  docker-build-image:
    name: Build images
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/docker/cli-multi@master
    - run:  docker-compose build

  zkp-setup:
    needs: [eslint, docker-build-image]
    name: Generate the keys and constraint files for Zero Knowledge Proofs
    runs-on: ubuntu-16.04

    steps:
    - run: npm run setupAll 