name: Run Nightfall Integration test

on:
  push:
    branches:
    - liju.jose/configure-github-actions

jobs:
  integration-test:
    name: Run integration test suits.
    runs-on: macOS-10.14
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.15.3'
    - run: npm ci
    - run: npm run lint
    - run: ls
